services:
  postgres-primary:
    image: docker.io/postgres:18-alpine
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATABASE=${DATABASE_NAME}
    volumes:
      - primary_postgres_data:/var/lib/postgresql/18/docker
      - ./postgresql/primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgresql/primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgresql/primary/init:/docker-entrypoint-initdb.d
    command: >
      postgres
        -c config_file=/etc/postgresql/postgresql.conf
        -c hba_file=/etc/postgresql/pg_hba.conf
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-replica:
    image: docker.io/postgres:18-alpine
    user: postgres
    environment:
      PGPASSWORD: ${REPLICATOR_PASSWORD}
    volumes:
      - ./postgresql/replica/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgresql/replica/start-replica.sh:/start-replica.sh
    command: sh /start-replica.sh
    depends_on:
      postgres-primary:
        condition: service_healthy

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      postgres-primary:
        condition: service_healthy
    restart: unless-stopped

volumes:
  primary_postgres_data: