global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend'
    dns_sd_configs:
      - names:
          - backend
        type: A
        port: 8000

  - job_name: 'postgres-primary'
    static_configs:
      - targets: ['postgres-exporter-primary:9187']

  - job_name: 'postgres-replica-1'
    static_configs:
      - targets: ['postgres-exporter-replica-1:9187']

  - job_name: 'postgres-replica-2'
    static_configs:
      - targets: ['postgres-exporter-replica-2:9187']