api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

accessLog:
  bufferingSize: 250
  filters:
    statusCodes:
      - "400-599"

log:
  level: INFO
