# Listen to all addresses or at least the container IP
listen_addresses = '*'

# Enable read queries while applying WAL changes
hot_standby = on

# Tell the primary which rows the replica still needs
# Prevents vacuuming rows that a long-running read query on the replica still references
hot_standby_feedback = on

# Performance
shared_buffers = 256MB
work_mem = 4MB